### ISSUE TITLE
Linking to specific component examples

### ISSUE THREAD

**Issue by ashireman** [vuetifyjs/docs#175]
Adding a visible anchor would allow providing links to specific examples.

Each example for a given component already has an id which would allow linking directly to the example usually in the format of "example-{1, 2, 3...}". If desired a url friendly name could be given to the anchor as well so that in the image below the link would be:

https://vuetifyjs.com/components/selects#autocomplete

Instead of:

https://vuetifyjs.com/components/selects#example-5

![link](https://user-images.githubusercontent.com/1223769/29462046-d1316354-83e2-11e7-846c-a298ef9e724a.jpg)

**Comment by nekosaur** [comment]
We've looked into this before, but there is some problem with hashes getting removed from the URL by nginx. @johnleider knows more.

**Comment by johnleider** [comment]
Long story short, proxied requests from nginx (I'm sure apache as well) do not maintain any hash sent over.

I'm all ears if someone has a solution to that.

**Comment by dbjoomla** [comment]
I've tried and in fact the tag is not recognized as part of the url, so it is not sent to the server but is solved by the client.

I've seen if you can not open the page from the link, but then, if you have changed the url and add anchor tag then go to the point.

since the value is resolved from the client, can it be enough to add the javascript function to the page, which splits the url, and takes you to the page's point? :)

with js split url and get a value
var point = document.getElementById (varwithvalue);
pointgo.scrollIntoView (pointgo);

i've tried with mdofied the page, and add another div with id form exaple, and it works.

How about? :)

**Comment by johnleider** [comment]
Can you elaborate on your findings? What you did, the process, how we might implement it. Thank you

**Comment by bdeo** [comment]
Though there is not a solution right now, if/when one is found, it would also be helpful to have these anchors at the prop level on the API table at the bottom of the docs.

**Comment by dbweb-io** [comment]
Hi @johnleider :) 
I am not familiar with nginx, so i do not know if the doc installation, how it is composed, who returned by the server, can create direct problems. ( In case I could install nginx and get rid of :) )

But I was referring to a function in js that when loading the page,verify hashtag presence in the url, fetches the content and bring you to the id wanted :)

I created a codepen ( after us method distribuited, i've make it a mod so all is in mounted, short possible ), for the occasion I think it's also good because opening the link here in a new window simulates the experience that a user can have when clicking on a link from 0 to the desired section of the doc:

https://codepen.io/dbweb/pen/yzgoWM#idtakefromhashtag

Do you think it is feasible / possible to integrate it, respecting the composition / structure of the doc installation?

I ask you why I do not know if it can be fine or be a good practice to call the car's function to load on each page

Have ever a good day ;)

**Comment by johnleider** [comment]
I understand how that works traditionally. The problem though, is with SSR, the application is proxied by a forward facing web-server. In our case, that is nginx. When a request comes through, the proxied requests are stripped of their hash and never even make it to the local application.

**Comment by dbweb-io** [comment]
Azz... now i understand... with this logic, and the rules/logic back under #anchor, the value is not passed anyway.... 
i want to deepen the use and the knowledge of nginx and vuetify ssr, always to create dashboards;)..... if i can solve it I put here all :)
Thanks Man

**Comment by dbweb-io** [comment]
p.s. in the common use on the web (nginx yet ) i see use & to pass value from url, using nginx.. can possible thing to use this for emulate anchor tag? perhaps with the word/reference key for the function in ssr who can elaborate after? 

for example:

https://vuetifyjs.com/quick-start&anchortag=webpack-ssr

:)

**Comment by johnleider** [comment]
It's something we can experiment with, thank you for looking into it.
