### ISSUE TITLE
How would I read the documentation offline?

### ISSUE THREAD

**Issue by abrhambas01** [vuetifyjs/docs#392]
I don't have an internet in my house. Maybe I can ask if How can I read the documentation offlineif I have to download anything in the library.

**Comment by ThisTNTSquid** [comment]
Before you do anything, make sure your computer have [**NodeJS**](https://nodejs.org/en/) installed first, because the documentation server runs on NodeJS. (If you do not have it installed on your computer, choose a version at your desire and install it) (I like cutting-edge stuff, so I have the latest installed and always keeping it up to date)

OK, let's get started.

Firstly, clone the repository to your computer with 
```bash
$ git clone https://github.com/vuetifyjs/docs.git
```
This will give you the the content inside `master` branch
Then inside the cloned folder, run 
```bash
# If you do not have yarn installed (use npm that came along with nodejs)
$ npm install 

# If you got yarnpkg
$ yarn 
```
This will install all the dependencies for you. 
> **Notice** This process takes up quite a lot of time, depending on the I/O speed of your hard disk and some CPU. So, relax and take a cup of coffee while waiting. If you don't want to wait that long, consider using [**Yarn Package Manager**](https://yarnpkg.com/), it works the exact same as NPM, but with a ***MUCH*** faster speed than NPM

After finished installing the dependencies, you are ready to launch a server for the documentation with
```bash
$ npm run dev
```
This will start up a development server for the vuetifyjs site (including the docs) (actually it is the exact same copy you see on [https://vuetifyjs.com/](https://vuetifyjs.com/).


Finally , after the server finished setting up, point your browser to `http://localhost:8080` , and **viola!** A complete offline version of the vuetifyjs website is now in front of you

**Comment by ThisTNTSquid** [comment]
if you're finished with the server, do Ctrl-C in the terminal, and it will stop

**Comment by abrhambas01** [comment]
Ahh just an ordinary npm project. Ok THanks

**Comment by abrhambas01** [comment]
Thank you @ThisTNTSquid for helping me.
